import test from "node:test";
import assert from "node:assert/strict";
import { createStructuredResponse, createImageResponse } from "../cloudflare/src/ai/openai.ts";
import { deliverNotification } from "../cloudflare/src/notifications.ts";
import worker from "../cloudflare/src/index.ts";
import { encryptSecret } from "../cloudflare/src/security.ts";
import { workspace } from "./workspace.mjs";

const options = {
  instructions: "Use brand rules",
  content: [{ type: "input_text", text: "Caption" }],
  schemaName: "test",
  schema: { type: "object" },
};

test("OpenAI mock verifies strict structured requests and response provenance", async (t) => {
  let sent;
  t.mock.method(globalThis, "fetch", async (url, init) => {
    assert.equal(url, "https://api.openai.com/v1/responses");
    sent = JSON.parse(init.body);
    assert.equal(init.headers.authorization, "Bearer fixture-key");
    return Response.json(
      {
        id: "response-1",
        output: [{ content: [{ type: "output_text", text: '{"caption":"On brand"}' }] }],
        usage: { output_tokens: 8 },
      },
      { headers: { "x-request-id": "request-1" } },
    );
  });
  const result = await createStructuredResponse({ OPENAI_API_KEY: "fixture-key" }, options);
  assert.equal(sent.text.format.strict, true);
  assert.equal(sent.text.format.name, "test");
  assert.equal(result.data.caption, "On brand");
  assert.equal(result.requestId, "request-1");
  assert.equal(result.responseId, "response-1");
});

test("OpenAI empty, malformed JSON and HTTP failures become actionable errors", async (t) => {
  const scenarios = [
    [Response.json({ output_text: "" }), /no structured text/],
    [Response.json({ output_text: "invalid-json" }), /invalid structured JSON/],
    [
      new Response("Rate limited", { status: 429, headers: { "x-request-id": "rate-test" } }),
      /429.*rate-test/,
    ],
  ];
  for (const [response, expected] of scenarios) {
    t.mock.method(globalThis, "fetch", async () => response);
    await assert.rejects(
      createStructuredResponse({ OPENAI_API_KEY: "fixture-key" }, options),
      expected,
    );
    t.mock.restoreAll();
  }
});

test("image mock preserves edit intent, JPEG output and generated bytes", async (t) => {
  t.mock.method(globalThis, "fetch", async (_url, init) => {
    const sent = JSON.parse(init.body);
    assert.equal(sent.tools[0].action, "edit");
    assert.equal(sent.tools[0].output_format, "jpeg");
    assert.equal(sent.tools[0].model, "fixture-edit-model");
    return Response.json({
      output: [
        {
          type: "image_generation_call",
          result: Buffer.from("jpeg-bytes").toString("base64"),
          revised_prompt: "Revised",
        },
      ],
    });
  });
  const result = await createImageResponse(
    { OPENAI_API_KEY: "fixture-key", OPENAI_IMAGE_EDIT_MODEL: "fixture-edit-model" },
    { instructions: "Keep the logo", prompt: "Brighten photo", action: "edit" },
  );
  assert.equal(Buffer.from(result.bytes).toString(), "jpeg-bytes");
  assert.equal(result.revisedPrompt, "Revised");
});

test("Resend and Expo mocks track partial delivery and escape user-provided email content", async (t) => {
  const w = workspace(t);
  w.exec(
    "INSERT INTO device_push_tokens(id,user_id,expo_push_token) VALUES ('device','owner','ExponentPushToken[test]')",
  );
  t.mock.method(globalThis, "fetch", async (url, init) => {
    if (url === "https://api.resend.com/emails") {
      const body = JSON.parse(init.body);
      assert.equal(body.html.includes("&lt;script&gt;"), true);
      assert.equal(body.html.includes("<script>"), false);
      return Response.json({ message: "Domain not verified" }, { status: 403 });
    }
    assert.equal(url, "https://exp.host/--/api/v2/push/send");
    return Response.json({ data: { status: "ok", id: "push-ticket" } });
  });
  const result = await deliverNotification(w.env, {
    userId: "owner",
    type: "published",
    title: "<script>",
    body: "Launch",
  });
  assert.equal(result.status, "partial");
  assert.equal(
    w.row("SELECT provider_message_id FROM notification_deliveries WHERE channel='push'")
      .provider_message_id,
    "push-ticket",
  );
  assert.equal(
    w.row("SELECT status FROM notification_deliveries WHERE channel='email'").status,
    "failed",
  );
});

async function publishingFixture(t) {
  const w = workspace(t);
  w.post("publish", "client-a", "calendar_scheduled");
  w.objects.set("graphic.jpg", "fixture image");
  w.exec(
    "INSERT INTO social_accounts(id,client_id,platform,external_account_id,status,access_token_ciphertext) VALUES ('social','client-a','facebook','fixture-page','connected',?)",
    await encryptSecret("fixture-token", w.env),
  );
  w.exec(
    "UPDATE posts SET social_account_id='social',graphic_key='graphic.jpg' WHERE id='publish'",
  );
  await w.request("/v1/posts/publish/publish-now", { user: "owner", method: "POST" });
  return w;
}

test("Meta queue mock confirms publication once despite duplicate deliveries and notifies owners", async (t) => {
  const w = await publishingFixture(t);
  let calls = 0,
    acknowledged = 0;
  t.mock.method(globalThis, "fetch", async (url) => {
    if (url.startsWith("https://graph.facebook.com/")) {
      calls++;
      return Response.json({ id: "photo", post_id: "published-id" });
    }
    assert.equal(url, "https://api.resend.com/emails");
    return Response.json({ id: "email-id" });
  });
  const message = {
    body: w.published[0],
    attempts: 1,
    ack() {
      acknowledged++;
    },
    retry() {
      throw new Error("Unexpected retry");
    },
  };
  await worker.queue({ messages: [message, message] }, w.env);
  assert.equal(calls, 1);
  assert.equal(acknowledged, 2);
  assert.equal(w.row("SELECT status FROM posts WHERE id='publish'").status, "published");
  assert.equal(w.row("SELECT status FROM publish_jobs").status, "completed");
  assert.equal(w.row("SELECT status FROM notifications WHERE type='published'").status, "sent");
});

test("provider rate limit retries without reporting the post as published", async (t) => {
  const w = await publishingFixture(t);
  t.mock.method(globalThis, "fetch", async () =>
    Response.json(
      { error: { message: "Rate limit", code: 4 } },
      { status: 429, headers: { "retry-after": "120" } },
    ),
  );
  let retry;
  await worker.queue(
    {
      messages: [
        {
          body: w.published[0],
          attempts: 1,
          ack() {
            throw new Error("Should retry");
          },
          retry(options) {
            retry = options;
          },
        },
      ],
    },
    w.env,
  );
  assert.equal(retry.delaySeconds >= 60, true);
  assert.equal(w.row("SELECT status FROM publish_jobs").status, "retrying");
  assert.equal(w.row("SELECT status FROM posts WHERE id='publish'").status, "publish_queued");
});
